/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
import { rest } from 'mswx';
import { faker } from '@faker-js/faker';
import { generateMock } from '@anatine/zod-mock';
import { schemas } from '../../src/api/api.client';

faker.seed(1);

const MAX_ARRAY_LENGTH = 20;

interface Nexts {
	[key: string]: number;
}
const nexts: Nexts = {};
let nextValue = 0;

const NextMiddleware = rest.middleware((req, res, ctx, next) => {
	const { pathname } = req.url;
	if (!nexts[pathname]) {
		nexts[pathname] = 0;
	}
	// nextValue = nexts[pathname]++;
	nextValue = 0;
	return next();
});

rest.config.API_PREFIX = 'http://localhost:8000/api/v1';
export const handlers = [
	rest.get(`/events`, (_, res, ctx) => {
		const resultArray = [
			[ctx.status(200), ctx.json(getGetAllEvents200Response())],
			[ctx.status(500), ctx.json(getGetAllEvents500Response())]
		];

		return res(...resultArray[nextValue % resultArray.length]);
	}),
	rest.post(`/events`, (_, res, ctx) => {
		const resultArray = [
			[ctx.status(200), ctx.json(getCreateEvent200Response())],
			[ctx.status(400), ctx.json(getCreateEvent400Response())],
			[ctx.status(403), ctx.json(getCreateEvent403Response())],
			[ctx.status(500), ctx.json(getCreateEvent500Response())]
		];

		return res(...resultArray[nextValue % resultArray.length]);
	}),
	rest.get(`/events/:eventId`, (_, res, ctx) => {
		const resultArray = [
			[ctx.status(200), ctx.json(getGetEvent200Response())],
			[ctx.status(404), ctx.json(getGetEvent404Response())],
			[ctx.status(500), ctx.json(getGetEvent500Response())]
		];

		return res(...resultArray[nextValue % resultArray.length]);
	}),
	rest.patch(`/events/:eventId`, (_, res, ctx) => {
		const resultArray = [
			[ctx.status(200), ctx.json(getUpdateEvent200Response())],
			[ctx.status(400), ctx.json(getUpdateEvent400Response())],
			[ctx.status(404), ctx.json(getUpdateEvent404Response())],
			[ctx.status(500), ctx.json(getUpdateEvent500Response())]
		];

		return res(...resultArray[nextValue % resultArray.length]);
	}),
	rest.delete(`/events/:eventId`, (_, res, ctx) => {
		const resultArray = [
			[ctx.status(200), ctx.json(getDeleteEvent200Response())],
			[ctx.status(403), ctx.json(getDeleteEvent403Response())],
			[ctx.status(404), ctx.json(getDeleteEvent404Response())],
			[ctx.status(500), ctx.json(getDeleteEvent500Response())]
		];

		return res(...resultArray[nextValue % resultArray.length]);
	}),
	rest.put(`/events/:eventId/join`, (_, res, ctx) => {
		const resultArray = [
			[ctx.status(200), ctx.json(getJoinEvent200Response())],
			[ctx.status(400), ctx.json(getJoinEvent400Response())],
			[ctx.status(403), ctx.json(getJoinEvent403Response())],
			[ctx.status(404), ctx.json(getJoinEvent404Response())],
			[ctx.status(500), ctx.json(getJoinEvent500Response())]
		];

		return res(...resultArray[nextValue % resultArray.length]);
	}),
	rest.post(`/events/:eventId/leave`, (_, res, ctx) => {
		const resultArray = [
			[ctx.status(200), ctx.json(getLeaveEvent200Response())],
			[ctx.status(404), ctx.json(getLeaveEvent404Response())],
			[ctx.status(500), ctx.json(getLeaveEvent500Response())]
		];

		return res(...resultArray[nextValue % resultArray.length]);
	}),
	rest.get(`/events/:eventId/msgs`, (_, res, ctx) => {
		const resultArray = [
			[ctx.status(200), ctx.json(getGetEventMsgs200Response())],
			[ctx.status(404), ctx.json(getGetEventMsgs404Response())],
			[ctx.status(500), ctx.json(getGetEventMsgs500Response())]
		];

		return res(...resultArray[nextValue % resultArray.length]);
	}),
	rest.post(`/events/:eventId/msgs`, (_, res, ctx) => {
		const resultArray = [
			[ctx.status(200), ctx.json(getCreateEventMsg200Response())],
			[ctx.status(403), ctx.json(getCreateEventMsg403Response())],
			[ctx.status(404), ctx.json(getCreateEventMsg404Response())],
			[ctx.status(500), ctx.json(getCreateEventMsg500Response())]
		];

		return res(...resultArray[nextValue % resultArray.length]);
	}),
	rest.get(`/categories`, (_, res, ctx) => {
		const resultArray = [
			[ctx.status(200), ctx.json(getGetCategories200Response())],
			[ctx.status(500), ctx.json(getGetCategories500Response())]
		];

		return res(...resultArray[nextValue % resultArray.length]);
	}),
	rest.post(`/login`, (_, res, ctx) => {
		const resultArray = [
			[ctx.status(303), ctx.json(null)],
			[ctx.status(401), ctx.json(getLogin401Response())],
			[ctx.status(409), ctx.json(getLogin409Response())],
			[ctx.status(500), ctx.json(getLogin500Response())]
		];

		return res(...resultArray[nextValue % resultArray.length]);
	}),
	rest.post(`/logout`, (_, res, ctx) => {
		const resultArray = [
			[ctx.status(200), ctx.json(getLogout200Response())],
			[ctx.status(500), ctx.json(getLogout500Response())]
		];

		return res(...resultArray[nextValue % resultArray.length]);
	}),
	rest.get(`/users/:userId`, (_, res, ctx) => {
		const resultArray = [
			[ctx.status(200), ctx.json(getGetUserInfo200Response())],
			[ctx.status(403), ctx.json(getGetUserInfo403Response())],
			[ctx.status(500), ctx.json(getGetUserInfo500Response())]
		];

		return res(...resultArray[nextValue % resultArray.length]);
	}),
	rest.patch(`/users/:userId`, (_, res, ctx) => {
		const resultArray = [
			[ctx.status(200), ctx.json(getUpdateUserInfo200Response())],
			[ctx.status(403), ctx.json(getUpdateUserInfo403Response())],
			[ctx.status(500), ctx.json(getUpdateUserInfo500Response())]
		];

		return res(...resultArray[nextValue % resultArray.length]);
	}),
	rest.get(`/users/:userId/events`, (_, res, ctx) => {
		const resultArray = [
			[ctx.status(200), ctx.json(getGetUserEvents200Response())],
			[ctx.status(404), ctx.json(getGetUserEvents404Response())],
			[ctx.status(500), ctx.json(getGetUserEvents500Response())]
		];

		return res(...resultArray[nextValue % resultArray.length]);
	})
].map(NextMiddleware);

export function getGetAllEvents200Response() {
	return [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) =>
		generateMock(schemas.Event)
	);
}

export function getGetAllEvents500Response() {
	return generateMock(schemas.DefaultError);
}

export function getCreateEvent200Response() {
	return generateMock(schemas.Event);
}

export function getCreateEvent400Response() {
	return generateMock(schemas.DefaultError);
}

export function getCreateEvent403Response() {
	return generateMock(schemas.DefaultError);
}

export function getCreateEvent500Response() {
	return generateMock(schemas.DefaultError);
}

export function getGetEvent200Response() {
	return generateMock(schemas.Event);
}

export function getGetEvent404Response() {
	return generateMock(schemas.DefaultError);
}

export function getGetEvent500Response() {
	return generateMock(schemas.DefaultError);
}

export function getUpdateEvent200Response() {
	return generateMock(schemas.Event);
}

export function getUpdateEvent400Response() {
	return generateMock(schemas.DefaultError);
}

export function getUpdateEvent404Response() {
	return generateMock(schemas.DefaultError);
}

export function getUpdateEvent500Response() {
	return generateMock(schemas.DefaultError);
}

export function getDeleteEvent200Response() {
	return generateMock(schemas.DefaultMsg);
}

export function getDeleteEvent403Response() {
	return generateMock(schemas.DefaultError);
}

export function getDeleteEvent404Response() {
	return generateMock(schemas.DefaultError);
}

export function getDeleteEvent500Response() {
	return generateMock(schemas.DefaultError);
}

export function getJoinEvent200Response() {
	return generateMock(schemas.DefaultMsg);
}

export function getJoinEvent400Response() {
	return generateMock(schemas.DefaultError);
}

export function getJoinEvent403Response() {
	return generateMock(schemas.DefaultError);
}

export function getJoinEvent404Response() {
	return generateMock(schemas.DefaultError);
}

export function getJoinEvent500Response() {
	return generateMock(schemas.DefaultError);
}

export function getLeaveEvent200Response() {
	return generateMock(schemas.DefaultMsg);
}

export function getLeaveEvent404Response() {
	return generateMock(schemas.DefaultError);
}

export function getLeaveEvent500Response() {
	return generateMock(schemas.DefaultError);
}

export function getGetEventMsgs200Response() {
	return [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) =>
		generateMock(schemas.EventMsg)
	);
}

export function getGetEventMsgs404Response() {
	return generateMock(schemas.DefaultError);
}

export function getGetEventMsgs500Response() {
	return generateMock(schemas.DefaultError);
}

export function getCreateEventMsg200Response() {
	return [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) =>
		generateMock(schemas.EventMsg)
	);
}

export function getCreateEventMsg403Response() {
	return generateMock(schemas.DefaultError);
}

export function getCreateEventMsg404Response() {
	return generateMock(schemas.DefaultError);
}

export function getCreateEventMsg500Response() {
	return generateMock(schemas.DefaultError);
}

export function getGetCategories200Response() {
	return [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map(
		(_) => null
	);
}

export function getGetCategories500Response() {
	return generateMock(schemas.DefaultError);
}

export function getLogin401Response() {
	return generateMock(schemas.DefaultError);
}

export function getLogin409Response() {
	return generateMock(schemas.DefaultError);
}

export function getLogin500Response() {
	return generateMock(schemas.DefaultError);
}

export function getLogout200Response() {
	return generateMock(schemas.DefaultMsg);
}

export function getLogout500Response() {
	return generateMock(schemas.DefaultError);
}

export function getGetUserInfo200Response() {
	return generateMock(schemas.User);
}

export function getGetUserInfo403Response() {
	return generateMock(schemas.DefaultError);
}

export function getGetUserInfo500Response() {
	return generateMock(schemas.DefaultError);
}

export function getUpdateUserInfo200Response() {
	return generateMock(schemas.User);
}

export function getUpdateUserInfo403Response() {
	return generateMock(schemas.DefaultError);
}

export function getUpdateUserInfo500Response() {
	return generateMock(schemas.DefaultError);
}

export function getGetUserEvents200Response() {
	return [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) =>
		generateMock(schemas.Event)
	);
}

export function getGetUserEvents404Response() {
	return generateMock(schemas.DefaultError);
}

export function getGetUserEvents500Response() {
	return generateMock(schemas.DefaultError);
}
